#!/usr/bin/env python
#
# Read infomations from a mobile provision file
#
# Copyright (c) 2015 by Yincp (yincp@126.com). All rights reserved.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#---------------------------------------------------------------------

from pprint import pprint
import sys
import os
import re
import zipfile, json
from biplist import *



def main(src_fd, dest_fd):
    try:
        plist = readPlist(src_fd)
        print json.dumps(plist, indent=4)
        writePlist(plist, dest_fd)
    except (InvalidPlistException, NotBinaryPlistException), e:
        print "Not a plist:", e

# end main()

if __name__ == '__main__':
    # modify_xcent('/Users/yincp/Downloads/test/archived-expanded-entitlements.xcent')
    main(sys.argv[1], sys.argv[2])
    sys.exit(0)
